// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: xc_protoc.proto at 12:1
package com.pix.xcserverlibrary.protobuf;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * 心跳返回
 */
public final class XCAliveACK extends Message<XCAliveACK, XCAliveACK.Builder> {
  public static final ProtoAdapter<XCAliveACK> ADAPTER = new ProtoAdapter_XCAliveACK();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_SERVERTIME = 0L;

  /**
   * 服务端时间戳
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#UINT64"
  )
  public final Long serverTime;

  public XCAliveACK(Long serverTime) {
    this(serverTime, ByteString.EMPTY);
  }

  public XCAliveACK(Long serverTime, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.serverTime = serverTime;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.serverTime = serverTime;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof XCAliveACK)) return false;
    XCAliveACK o = (XCAliveACK) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(serverTime, o.serverTime);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (serverTime != null ? serverTime.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (serverTime != null) builder.append(", serverTime=").append(serverTime);
    return builder.replace(0, 2, "XCAliveACK{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<XCAliveACK, Builder> {
    public Long serverTime;

    public Builder() {
    }

    /**
     * 服务端时间戳
     */
    public Builder serverTime(Long serverTime) {
      this.serverTime = serverTime;
      return this;
    }

    @Override
    public XCAliveACK build() {
      return new XCAliveACK(serverTime, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_XCAliveACK extends ProtoAdapter<XCAliveACK> {
    ProtoAdapter_XCAliveACK() {
      super(FieldEncoding.LENGTH_DELIMITED, XCAliveACK.class);
    }

    @Override
    public int encodedSize(XCAliveACK value) {
      return (value.serverTime != null ? ProtoAdapter.UINT64.encodedSizeWithTag(1, value.serverTime) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, XCAliveACK value) throws IOException {
      if (value.serverTime != null) ProtoAdapter.UINT64.encodeWithTag(writer, 1, value.serverTime);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public XCAliveACK decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.serverTime(ProtoAdapter.UINT64.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public XCAliveACK redact(XCAliveACK value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
