// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: xc_protoc.proto at 38:1
package com.pix.xcserverlibrary.protobuf;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

/**
 * 服务器通知连接关闭
 */
public final class XCServerCloseBRO extends Message<XCServerCloseBRO, XCServerCloseBRO.Builder> {
  public static final ProtoAdapter<XCServerCloseBRO> ADAPTER = new ProtoAdapter_XCServerCloseBRO();

  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_MSG = "";

  /**
   * 关闭消息
   */
  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING"
  )
  public final String msg;

  public XCServerCloseBRO(String msg) {
    this(msg, ByteString.EMPTY);
  }

  public XCServerCloseBRO(String msg, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.msg = msg;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.msg = msg;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof XCServerCloseBRO)) return false;
    XCServerCloseBRO o = (XCServerCloseBRO) other;
    return Internal.equals(unknownFields(), o.unknownFields())
        && Internal.equals(msg, o.msg);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (msg != null ? msg.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (msg != null) builder.append(", msg=").append(msg);
    return builder.replace(0, 2, "XCServerCloseBRO{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<XCServerCloseBRO, Builder> {
    public String msg;

    public Builder() {
    }

    /**
     * 关闭消息
     */
    public Builder msg(String msg) {
      this.msg = msg;
      return this;
    }

    @Override
    public XCServerCloseBRO build() {
      return new XCServerCloseBRO(msg, buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_XCServerCloseBRO extends ProtoAdapter<XCServerCloseBRO> {
    ProtoAdapter_XCServerCloseBRO() {
      super(FieldEncoding.LENGTH_DELIMITED, XCServerCloseBRO.class);
    }

    @Override
    public int encodedSize(XCServerCloseBRO value) {
      return (value.msg != null ? ProtoAdapter.STRING.encodedSizeWithTag(1, value.msg) : 0)
          + value.unknownFields().size();
    }

    @Override
    public void encode(ProtoWriter writer, XCServerCloseBRO value) throws IOException {
      if (value.msg != null) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.msg);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public XCServerCloseBRO decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.msg(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            FieldEncoding fieldEncoding = reader.peekFieldEncoding();
            Object value = fieldEncoding.rawProtoAdapter().decode(reader);
            builder.addUnknownField(tag, fieldEncoding, value);
          }
        }
      }
      reader.endMessage(token);
      return builder.build();
    }

    @Override
    public XCServerCloseBRO redact(XCServerCloseBRO value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
